version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./.env.dev
    volumes:
      - ./data/psql:/var/lib/postgresql/data
